---

- name: Setup network
  hosts: default
  become: true
  tasks:
    - name: Copy network settings
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "/home/ural/network_setup/wp2/99_config.yaml", dest: "/etc/netplan/99_config.yaml"}
    - name: Change hostname
      command: sudo hostnamectl set-hostname wp2
    - name: Apply config
      command: sudo netplan apply 99
    

